import os
import re
from utils.io_utils import send_prompt_to_llm
from utils.io_utils import load_prompt_template
from utils.io_utils import save_result

PROMPT_PATH = "prompts/failure_analysis_prompt.txt"
FAILURE_OUTPUT_PATH = "results/failure_output.txt"
ANALYSIS_REPORT_PATH = "results/failure_analysis_report.txt"  # Path to save the analysis report

def analyze_failures_with_llm(failure_text, api_url="http://127.0.0.1:1234"):

    # Read the prompt template
    prompt = load_prompt_template(PROMPT_PATH)

    # Format the prompt with the failure text
    prompt = prompt.format(failures=failure_text)

    # Use shared utility function to send the prompt to the LLM
    try:
        analysis = send_prompt_to_llm(prompt, api_url=api_url)
        if not analysis:
            raise ValueError("No analysis generated by the model.")
        return analysis
    except Exception as e:
        raise Exception(f"An error occurred while generating tests: {e}")

def extract_failures_from_file(file_path):
    # Extract failing test messages from a saved file.

    if not os.path.exists(file_path):
        raise FileNotFoundError(f"Failure output file not found at: {file_path}")

    with open(file_path, "r") as f:
        pytest_output = f.read()

    match = re.search(r"=+ FAILURES =+(.*?)(=+ short test summary info =+)", pytest_output, re.DOTALL)
    if match:
        return match.group(1).strip()
    else:
        return pytest_output  # fallback

def main():
    # Main function to orchestrate the failure analysis process.
    
    try:
        # Extract failure details from the failure output file
        failure_details = extract_failures_from_file(FAILURE_OUTPUT_PATH)
        print("🔍 Extracted Failures:\n", failure_details)

        # Analyze the failures using the LLM
        analysis = analyze_failures_with_llm(failure_details)
        if analysis:
            print("\n🛠️ Suggested Fixes:\n")
            print(analysis)

            # Save the analysis report to a file
            save_result(analysis, ANALYSIS_REPORT_PATH)
    except FileNotFoundError as e:
        print(f"❌ {e}")

if __name__ == "__main__":
    main()